defaults:
  -
    scope:
      path: "notes" 
    values:
      layout: "note"
      author: "Maxime Tournier"


markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  toc_levels: 1..2

